services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: opinion_api
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:16
    container_name: opinion_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: opinion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
